name: new release

on:
  push:
    tags:
      - '*'
      # git tag v1.0.0
      # git push origin v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build
      run: go build -v -o app/templ8.exe

    - name: Create a Release
      uses: "marvinpinto/action-automatic-releases@latest"

      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }} # you don't have to create this, auto done by GitHub Actions
        prerelease: false
        title: Release  ${{ github.ref_name }}
        automatic_release_tag: ${{ github.ref_name }}
        files: |
          app/templ8.exe