name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Hello and welcome to our project! Thank you for opening an issue. We're excited to have you here and look forward to working together to improve this project. Please ensure you've provided all necessary details and followed the issue template (if applicable). Let's collaborate and resolve this promptly! 🚀"
        pr-message: "🎉 Thank you for your first contribution to our project! We're thrilled to see your PR and appreciate the effort you've put in. The team will review your submission soon. If you have any questions or need assistance, feel free to ask. Welcome aboard! 🌟"
